-- ============================================================
-- Migration 004: Practice, test, and worksheet tables
-- ============================================================

-- Practice sessions: MCQ practice rounds
create table if not exists public.practice_sessions (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject text not null,
  class_level integer not null,
  chapter text,
  difficulty text default 'mixed' check (difficulty in ('easy', 'medium', 'hard', 'mixed')),
  total_questions integer not null,
  correct_count integer default 0,
  questions jsonb not null default '[]',    -- array of {question, options, correct, selected, explanation}
  completed boolean default false,
  created_at timestamptz default now()
);

-- Test sessions: timed tests assigned by teacher or self-taken
create table if not exists public.test_sessions (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  subject text not null,
  class_level integer not null,
  total_marks integer not null,
  score integer,
  time_limit_minutes integer,
  time_taken_seconds integer,
  questions jsonb not null default '[]',
  ai_insights jsonb default '{}',           -- AI-generated performance analysis
  completed boolean default false,
  assigned_by uuid references public.profiles(id) on delete set null,  -- teacher who assigned
  created_at timestamptz default now(),
  completed_at timestamptz
);

-- Worksheets: generated by teachers
create table if not exists public.worksheets (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  subject text not null,
  class_level integer not null,
  chapter text,
  mode text default 'custom' check (mode in ('custom', 'mimic')),
  difficulty text default 'mixed',
  total_questions integer not null,
  sections jsonb not null default '[]',      -- array of {name, questions: [{question, answer, marks, validated}]}
  source_pdf text,                           -- for mimic mode: original PDF filename
  model_used text,
  created_at timestamptz default now()
);

-- Subject mastery: aggregated accuracy per student per subject
create table if not exists public.subject_mastery (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject text not null,
  accuracy_percent integer default 0 check (accuracy_percent between 0 and 100),
  total_questions integer default 0,
  correct_answers integer default 0,
  weak_topics jsonb default '[]',            -- array of topic strings
  strong_topics jsonb default '[]',
  last_updated timestamptz default now(),
  unique(student_id, subject)
);

-- Indexes
create index if not exists idx_practice_sessions_student on public.practice_sessions(student_id);
create index if not exists idx_test_sessions_student on public.test_sessions(student_id);
create index if not exists idx_worksheets_teacher on public.worksheets(teacher_id);
create index if not exists idx_subject_mastery_student on public.subject_mastery(student_id);
